### ISSUE TITLE
[Tracking] ERC-721 extensions

### ISSUE THREAD

**Issue by alexfertel** [OpenZeppelin/rust-contracts-stylus#10]
```[tasklist]
### Tasks
- [ ] https://github.com/OpenZeppelin/rust-contracts-stylus/issues/19
- [ ] https://github.com/OpenZeppelin/rust-contracts-stylus/issues/66
- [ ] https://github.com/OpenZeppelin/rust-contracts-stylus/issues/65
- [ ] https://github.com/OpenZeppelin/rust-contracts-stylus/issues/67
- [ ] https://github.com/OpenZeppelin/rust-contracts-stylus/issues/68
- [ ] https://github.com/OpenZeppelin/rust-contracts-stylus/issues/56
- [ ] https://github.com/OpenZeppelin/rust-contracts-stylus/issues/233
```

**Comment by bidzyyys** [comment]
Closing as all issues completed.
