### ISSUE TITLE
[Feature]: Gas Benchmark

### ISSUE THREAD

**Issue by ggonzalez94** [OpenZeppelin/rust-contracts-stylus#106]
### What is the feature you would like to see?

One of the benefits of using Stylus is potential gas savings(of course this depends on the specific contract). So I think it is important that we include a gas benchmark that compares our stylus implementation vs their solidity counterparts and include this in the `Readme` or other part of the repo.

A couple implementations for reference of how this could look like:
- https://github.com/cairoeth/rustmate?tab=readme-ov-file#-gas-benchmarks
- https://github.com/LimeChain/stylus-benchmark

### Contribution Guidelines

- [x] I agree to follow this project's Contribution Guidelines
```[tasklist]
### Tasks
- [ ] https://github.com/OpenZeppelin/rust-contracts-stylus/issues/167
- [ ] https://github.com/OpenZeppelin/rust-contracts-stylus/issues/171
- [ ] https://github.com/OpenZeppelin/rust-contracts-stylus/issues/172
- [ ] https://github.com/OpenZeppelin/rust-contracts-stylus/issues/173
- [ ] https://github.com/OpenZeppelin/rust-contracts-stylus/issues/174
- [ ] https://github.com/OpenZeppelin/rust-contracts-stylus/issues/169
```

**Comment by bidzyyys** [comment]
Closing as gas benches are added, only #170 to be considered in the future.
