### ISSUE TITLE
[Tracking] Ownable

### ISSUE THREAD

**Issue by alexfertel** [OpenZeppelin/rust-contracts-stylus#12]
```[tasklist]
### Tasks
- [ ] https://github.com/OpenZeppelin/rust-contracts-stylus/issues/137
- [ ] https://github.com/OpenZeppelin/rust-contracts-stylus/issues/206
- [ ] https://github.com/OpenZeppelin/rust-contracts-stylus/issues/136
```
