### ISSUE TITLE
[Tracking] Setup integration tests

### ISSUE THREAD

**Issue by alexfertel** [OpenZeppelin/rust-contracts-stylus#15]
This issue tracks the work required to set up the infrastructure for our integration test suite.

This work is mainly blocked because we need a reliable, fast way of booting up a local, Stylus-compatible fork. Ideally, we have something like [`anvil`](https://github.com/foundry-rs/foundry/tree/master/crates/anvil), provided by the Stylus team.

- [x] Spike: Create a PoC with `anvil` that showcases the missing pieces required to make it work with Stylus.
- [x] Spike: Research possible alternatives. 
```[tasklist]
### Tasks
- [ ] https://github.com/OpenZeppelin/rust-contracts-stylus/issues/53
- [ ] https://github.com/OpenZeppelin/rust-contracts-stylus/issues/72
- [ ] https://github.com/OpenZeppelin/rust-contracts-stylus/issues/81
```
