### ISSUE TITLE
[Tracking] ERC-20 token standard

### ISSUE THREAD

**Issue by alexfertel** [OpenZeppelin/rust-contracts-stylus#7]
```[tasklist]
### Tasks
- [x] ERC-20 base implementation
- [x] ERC-20 documentation
- [ ] https://github.com/OpenZeppelin/rust-contracts-stylus/issues/94
- [ ] https://github.com/OpenZeppelin/rust-contracts-stylus/issues/8
```

**Comment by bidzyyys** [comment]
Closing as all sub-issues are finished.
