### ISSUE TITLE
[Tracking] ERC-20 extensions

### ISSUE THREAD

**Issue by alexfertel** [OpenZeppelin/rust-contracts-stylus#8]
```[tasklist]
### Tasks
- [ ] https://github.com/OpenZeppelin/rust-contracts-stylus/issues/29
- [ ] https://github.com/OpenZeppelin/rust-contracts-stylus/issues/34
- [ ] https://github.com/OpenZeppelin/rust-contracts-stylus/issues/27
- [ ] https://github.com/OpenZeppelin/rust-contracts-stylus/issues/42
- [ ] https://github.com/OpenZeppelin/rust-contracts-stylus/issues/43
- [ ] https://github.com/OpenZeppelin/rust-contracts-stylus/issues/232
```

**Comment by bidzyyys** [comment]
Closing as all extensions are finished (and docs).
