### ISSUE TITLE
[Tracking] ERC-721 token standard

### ISSUE THREAD

**Issue by alexfertel** [OpenZeppelin/rust-contracts-stylus#9]
```[tasklist]
### Tasks
- [ ] https://github.com/OpenZeppelin/rust-contracts-stylus/issues/28
- [ ] https://github.com/OpenZeppelin/rust-contracts-stylus/issues/93
- [ ] https://github.com/OpenZeppelin/rust-contracts-stylus/issues/10
- [ ] https://github.com/OpenZeppelin/rust-contracts-stylus/issues/69
- [ ] https://github.com/OpenZeppelin/rust-contracts-stylus/issues/213
```

**Comment by bidzyyys** [comment]
Closing as all issues completed.
